---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nut_packages.
  set_fact:
    nut_packages: "{{ __nut_packages | list }}"
  when: nut_packages is not defined

- name: Ensure NUT packages are installed.
  package:
    name: "{{ nut_packages }}"
    state: present

- name: Define configuration files.
  set_fact:
    nut_configuration_files:
      - nut.conf
      - upsmon.conf

- name: Add ups.conf to configuration files.
  set_fact:
    nut_configuration_files: "{{ nut_configuration_files + ['ups.conf'] }}"
  when: '("nut-server" in nut_services) or ("nut-driver" in nut_services)'

- name: Add upsd.users and upsd.conf to configuration files.
  set_fact:
    nut_configuration_files: "{{ nut_configuration_files + ['upsd.users', 'upsd.conf'] }}"
  when: '"nut-server" in nut_services'

- name: Install NUT configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "{{__nut_config_dir}}{{ item }}"
    owner: root
    group: nut
    mode: 0640
  with_items: "{{ nut_configuration_files }}"
  notify: restart nut
  when: nut_managed_config

- name: Install custom notifycmd script.
  copy:
    dest: "{{ nut_upsmon_notifycmd }}"
    content: "{{ nut_upsmon_notifycmd_content }}"
    owner: root
    group: nut
    mode: 0770
  when: nut_upsmon_notifycmd_content is defined
